### ISSUE TITLE
Change "cdef"s to "cpdef"s

### ISSUE THREAD

**Issue by esayyari** [wasade/improved-octo-waddle#27]
Currently, it is not easy to use BP class attributes in python. Most of these methods were defined using "cdef". "cdef" basically means a c-only function which generally shouldn’t be called from python (there are always ways around, probably bad here as it’s nogil). "def" creates a python function which adds a lot of overhead. “cpdef” creates both a c and python function which is probably best. Please change "cdef"s to "cpdef"s so that BP class methods can be accessible from python as well.

**Comment by wasade** [comment]
Closing as I think this is already addressed -- most of the member methods are cpdef
